const SCREENS = {
  LOGIN: 'Login',
  PHONE_VERIFICATION: 'PhoneVerification',
  HOME: 'Home',
  HOME_SEARCH: 'HomeSearch',
  AWARD: 'Award',
  PROFILE: 'Profile',
  DRIVER_RIDE: 'DriverRide',
  PASSENGER_RIDE: 'PassengerRide',
  MATCHED_RIDE: 'MatchedRide',
  MESSAGE: 'Message',
  REPORT: 'Report',
  NOTIFICATION: 'Notification',
  MEMBER: 'Member',
  MEMBER_DETAIL: 'MemberDetail',
  VOUCHER: 'Voucher',
  MISSION: 'Mission',
  ADMIN_STACK: 'AdminStack',
  ADMIN_DASHBOARD: 'AdminDashboard',
  ADMIN_TRIP_MANAGEMENT: 'AdminTripManagement',
  ADMIN_USER_MANAGEMENT: 'AdminUserManagement',
  ADMIN_USER_DETAIL: 'AdminUserDetail',
  ADMIN_REPORT_MANAGEMENT: 'AdminReportManagement',
  ADMIN_REWARD_MANAGEMENT: 'AdminRewardManagement',
  ADMIN_PROFILE: 'AdminProfile',
  ADMIN_MEMBERSHIP_MANAGEMENT: 'MembershipManagement',
};

export default SCREENS;