const SCREENS = {
  ONBOARDING: "Onboarding",
  LOGIN: "Login",
  ID_CARD_CAPTURE: "IDCardCaptureScreen",
  LIVENESS_CHECK: "LivenessCheckScreen",
  PHONE_NUMBER_INPUT: "PhoneNumberInput",
  PHONE_VERIFICATION: "PhoneVerification",
  REGISTER_COMPLETE: "RegisterComplete",
  HOME: "Home",
  HOME_SEARCH: "HomeSearch",
  AWARD: "Award",
  PROFILE: "Profile",
  DRIVER_RIDE: "DriverRide",
  DRIVER_RIDE_REQUESTS: "DriverRideRequests",
  DRIVER_STATUS: "DriverStatus",
  DRIVER_MAP: "DriverMap",
  PASSENGER_RIDE: "PassengerRide",
  MATCHED_RIDE: "MatchedRide",
  MESSAGE: "Message",
  REPORT: "Report",
  NOTIFICATION: "Notification",
  MEMBER: "Member",
  MEMBER_DETAIL: "MemberDetail",
  VOUCHER: "Voucher",
  MY_VOUCHERS: "MyVouchers",
  MISSION: "Mission",
  RIDE_HISTORY: "RideHistory",
  ADMIN_STACK: "AdminStack",
  ADMIN_DASHBOARD: "AdminDashboard",
  ADMIN_TRIP_MANAGEMENT: "AdminTripManagement",
  ADMIN_USER_MANAGEMENT: "AdminUserManagement",
  ADMIN_USER_DETAIL: "AdminUserDetail",
  ADMIN_REPORT_MANAGEMENT: "AdminReportManagement",
  ADMIN_REWARD_MANAGEMENT: "AdminRewardManagement",
  ADMIN_PROFILE: "AdminProfile",
  ADMIN_MEMBERSHIP_MANAGEMENT: "MembershipManagement",
  PAYMENT: "Payment",
  PAYMENT_HISTORY: "PaymentHistory",
};

export default SCREENS;
